linters:
  disable-all: true
  enable:
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - durationcheck
    - err113
    - errcheck
    - errname
    - gocritic
    - godox
    - gofmt
    - goimports
    - gosmopolitan
    - govet
    - grouper
    - ineffassign
    - misspell
    - nakedret
    - nilnil
    - noctx
    - perfsprint
    - prealloc
    - promlinter
    - protogetter
    - reassign
    - staticcheck
    - testifylint
