linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errorlint
    - errname
    - goconst
    - gocritic
    - godox
    - gofmt
    - goimports
    - gosmopolitan
    - govet
    - grouper
    - ineffassign
    - misspell
    - nakedret
    - nilnil
    - noctx
    - perfsprint
    - prealloc
    - promlinter
    - protogetter
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tenv
    - testifylint
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
