linters:
  disable-all: true
  enable:
    - bidichk
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - durationcheck
    - err113
    - errname
    - gocritic
    - godox
    - gofmt
    - goimports
    - govet
    - grouper
    - ineffassign
    - misspell
    - nakedret
    - nilnil

