---
version: 2
builds:
  - id: archived-cli
    main: ./cmd/cli
    binary: archived-cli
    ldflags:
      - -s -w -X main.appVersion={{.Version}} -X main.buildTimestamp={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goamd64: ["v1", "v2", "v3"]
    mod_timestamp: "{{ .CommitTimestamp }}"
  - id: archived-exporter
    main: ./cmd/exporter
    binary: archived-exporter
    ldflags:
      - -s -w -X main.appVersion={{.Version}} -X main.buildTimestamp={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goamd64: ["v1", "v2", "v3"]
    goarm: ["7"]
    mod_timestamp: "{{ .CommitTimestamp }}"
  - id: archived-gc
    main: ./cmd/gc
    binary: archived-gc
    ldflags:
      - -s -w -X main.appVersion={{.Version}} -X main.buildTimestamp={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goamd64: ["v1", "v2", "v3"]
    goarm: ["7"]
    mod_timestamp: "{{ .CommitTimestamp }}"
  - id: archived-manager
    main: ./cmd/manager
    binary: archived-manager
    ldflags:
      - -s -w -X main.appVersion={{.Version}} -X main.buildTimestamp={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goamd64: ["v1", "v2", "v3"]
    goarm: ["7"]
    mod_timestamp: "{{ .CommitTimestamp }}"
  - id: archived-migrator
    main: ./cmd/migrator
    binary: archived-migrator
    ldflags:
      - -s -w -X main.appVersion={{.Version}} -X main.buildTimestamp={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goamd64: ["v1", "v2", "v3"]
    goarm: ["7"]
    mod_timestamp: "{{ .CommitTimestamp }}"
  - id: archived-publisher
    main: ./cmd/publisher
    binary: archived-publisher
    ldflags:
      - -s -w -X main.appVersion={{.Version}} -X main.buildTimestamp={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goamd64: ["v1", "v2", "v3"]
    goarm: ["7"]
    mod_timestamp: "{{ .CommitTimestamp }}"
  - id: archived-seeder
    main: ./cmd/seeder
    binary: archived-seeder
    ldflags:
      - -s -w -X main.appVersion={{.Version}} -X main.buildTimestamp={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goamd64: ["v1", "v2", "v3"]
    goarm: ["7"]
    mod_timestamp: "{{ .CommitTimestamp }}"
archives:
  - format: binary
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
  split: false
  disable: false
