services:
  postgresql:
    image: postgres:16.3
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  minio:
    image: quay.io/minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command:
      - server
      - /data
    ports:
      - "9000:9000"
  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    environment:
      METADATA_DSN: postgres://postgres:password@postgresql?sslmode=disable
    depends_on:
      postgresql:
        condition: service_healthy
  access:
    build:
      context: .
      dockerfile: Dockerfile.access
    environment:
      METADATA_DSN: postgres://postgres:password@postgresql?sslmode=disable
      BLOB_S3_ENDPOINT: http://minio:9000
      BLOB_S3_BUCKET: test-bucket
      BLOB_S3_ACCESS_KEY_ID: minioadmin
      BLOB_S3_SECRET_KEY: minioadmin
    ports:
      - "8080:8080"
    depends_on:
      postgresql:
        condition: service_healthy
  manage:
    build:
      context: .
      dockerfile: Dockerfile.manage
    environment:
      METADATA_DSN: postgres://postgres:password@postgresql?sslmode=disable
      BLOB_S3_ENDPOINT: http://minio:9000
      BLOB_S3_BUCKET: test-bucket
      BLOB_S3_ACCESS_KEY_ID: minioadmin
      BLOB_S3_SECRET_KEY: minioadmin
    ports:
      - "5555:5555"
    depends_on:
      postgresql:
        condition: service_healthy

volumes:
  database:
  minio:
