FROM alpine:3.20.0 AS certificates

RUN apk add --update --no-cache \
  ca-certificates=20240705-r0

FROM scratch

COPY --from=certificates /etc/ssl/cert.pem /etc/ssl/cert.pem
COPY --chmod=0755 --chown=root:root dist/archived-migrate_linux_amd64_v3/archived-migrate /archived-migrate
COPY --chmod=0644 --chown=root:root repositories/metadata/postgresql/migrations/sql /migrations/sql

ENTRYPOINT [ "/archived-migrate" ]
