services:
  postgresql:
    image: ${IMAGE_PREFIX:-}index.docker.io/library/postgres:16.3
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: ${IMAGE_PREFIX:-}quay.io/minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command:
      - server
      - /data
      - "--address=:9000"
      - "--console-address=:9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9001"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
      start_interval: 5s

  migrator:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.migrator
      args:
        ALPINE_IMAGE: ${IMAGE_PREFIX:-}index.docker.io/library/alpine:3.20.3
    image: ${IMAGE_PREFIX:-}ghcr.io/teran/archived/migrator:latest
    environment:
      LOG_LEVEL: trace
      METADATA_DSN: postgres://postgres:password@postgresql?sslmode=disable
    depends_on:
      postgresql:
        condition: service_healthy
  publisher:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.publisher
      args:
        ALPINE_IMAGE: ${IMAGE_PREFIX:-}index.docker.io/library/alpine:3.20.3
        ARG NODE_IMAGE: ${IMAGE_PREFIX:-}index.docker.io/library/node:22.12.0
    image: ${IMAGE_PREFIX:-}ghcr.io/teran/archived/publisher:latest
    environment:
      LOG_LEVEL: trace
      METADATA_DSN: postgres://postgres:password@postgresql?sslmode=disable
      BLOB_S3_ENDPOINT: "${ARCHIVED_BLOB_S3_ENDPOINT:-http://minio:9000}"
      BLOB_S3_BUCKET: "${ARCHIVED_BLOB_S3_BUCKET:-test-bucket}"
      BLOB_S3_ACCESS_KEY_ID: minioadmin
      BLOB_S3_SECRET_KEY: minioadmin
    ports:
      - "8080:8080"
    depends_on:
      postgresql:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully

  manager:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.manager
      args:
        ALPINE_IMAGE: ${IMAGE_PREFIX:-}index.docker.io/library/alpine:3.20.3
    image: ${IMAGE_PREFIX:-}ghcr.io/teran/archived/manager:latest
    environment:
      LOG_LEVEL: trace
      METADATA_DSN: postgres://postgres:password@postgresql?sslmode=disable
      BLOB_S3_ENDPOINT: "${ARCHIVED_BLOB_S3_ENDPOINT:-http://minio:9000}"
      BLOB_S3_BUCKET: "${ARCHIVED_BLOB_S3_BUCKET:-test-bucket}"
      BLOB_S3_CREATE_BUCKET: "true"
      BLOB_S3_ACCESS_KEY_ID: minioadmin
      BLOB_S3_SECRET_KEY: minioadmin
    ports:
      - "5555:5555"
    depends_on:
      postgresql:
        condition: service_healthy
      minio:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully

  # seeder:
  #   build:
  #     context: .
  #     dockerfile: dockerfiles/Dockerfile.seeder
  #   image: ${IMAGE_PREFIX:-}ghcr.io/teran/archived/seeder:latest
  #   environment:
  #     LOG_LEVEL: info
  #     METADATA_DSN: postgres://postgres:password@postgresql?sslmode=disable
  #     BLOB_S3_CREATE_BUCKET: "true"
  #     BLOB_S3_ENDPOINT: http://minio:9000
  #     BLOB_S3_BUCKET: test-bucket
  #     BLOB_S3_ACCESS_KEY_ID: minioadmin
  #     BLOB_S3_SECRET_KEY: minioadmin
  #   depends_on:
  #     postgresql:
  #       condition: service_healthy
  #     minio:
  #       condition: service_healthy
  #     migrator:
  #       condition: service_completed_successfully

volumes:
  database:
  minio:
