FROM alpine:3.20.3 AS certificates

RUN apk add --update --no-cache \
  ca-certificates=20241121-r0

FROM scratch

COPY dockerfiles/rootfs/etc/passwd /etc/passwd
COPY dockerfiles/rootfs/etc/group /etc/group

COPY --from=certificates /etc/ssl/cert.pem /etc/ssl/cert.pem
COPY --chmod=0755 --chown=root:root dist/archived-cli_linux_amd64_v3/archived-cli /archived-cli

ENTRYPOINT [ "/archived-cli" ]
