FROM alpine:3.20.3 AS certificates

RUN apk add --update --no-cache \
  ca-certificates=20240705-r0

FROM scratch

COPY dockerfiles/rootfs/etc/passwd /etc/passwd
COPY dockerfiles/rootfs/etc/group /etc/group

COPY --from=certificates /etc/ssl/cert.pem /etc/ssl/cert.pem
COPY --chmod=0755 --chown=root:root dist/archived-gc_linux_amd64_v3/archived-gc /archived-gc

USER nobody

ENTRYPOINT [ "/archived-gc" ]
