---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: metadatadb
  namespace: archived
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3-7

  minSyncReplicas: 2
  maxSyncReplicas: 2

  postgresql:
    syncReplicaElectionConstraint:
      enabled: true
      nodeLabelsAntiAffinity:
        - topology.kubernetes.io/node
  
  replicationSlots:
    highAvailability:
      enabled: true
    updateInterval: 10

  primaryUpdateStrategy: unsupervised
  switchoverDelay: 60
  storage:
    pvcTemplate:
      resources:
        requests:
          storage: 30Gi
      storageClassName: openebs-hostpath
      volumeMode: Filesystem
    resizeInUseVolumes: false

  resources:
    requests:
      memory: "1Gi"
      cpu: 1
    limits:
      memory: "1Gi"
      cpu: 1

  backup:
    barmanObjectStore:
      destinationPath: "s3://<CHANGEME: backup bucket>"
      endpointURL: https://s3.example.com # (CHANGEME: s3 endpoint)
      s3Credentials:
        accessKeyId:
          name: cnpg-backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-backup-creds
          key: ACCESS_SECRET_KEY
    retentionPolicy: "30d"

  monitoring:
    enablePodMonitor: true
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: metadatadb-backups
  namespace: archived
spec:
  schedule: "0 58 */9 * * *"
  backupOwnerReference: self
  cluster:
    name: metadatadb
