---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archived-publisher
  namespace: archived
  labels:
    app.kubernetes.io/name: archived-publisher
    app.kubernetes.io/app: archived-publisher
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: archived-publisher
      app.kubernetes.io/app: archived-publisher
  template:
    metadata:
      labels:
        app.kubernetes.io/name: archived-publisher
        app.kubernetes.io/app: archived-publisher
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/app
                operator: In
                values:
                - archived-publisher
            topologyKey: "kubernetes.io/node"
      terminationGracePeriodSeconds: 30
      automountServiceAccountToken: false
      containers:
        - name: publisher
          image: ghcr.io/teran/archived/publisher:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: s3-blob-repository
            - secretRef:
                name: s3-blob-repository
          env:
            - name: METADATA_DSN
              valueFrom:
                secretKeyRef:
                  name: metadata-database-ro
                  key: METADATA_DSN_RO
            - name: LOG_LEVEL
              value: "trace"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              memory: 1Gi
          startupProbe:
            httpGet:
              path: /healthz/startup
              port: metrics
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthz/readiness
              port: metrics
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz/liveness
              port: metrics
            timeoutSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
