---
apiVersion: v1
stringData:
  ACCESS_KEY_ID: "<CHANGEME: backup-user-access-key-id>"
  ACCESS_SECRET_KEY: "<CHANGEME: backup-user-access-key-secret>"
kind: Secret
metadata:
  name: cnpg-backup-creds
  namespace: archived
type: Opaque
---
apiVersion: v1
stringData:
  BLOB_S3_ACCESS_KEY_ID: "<CHANGEME: blob-user-access-key-id>"
  BLOB_S3_SECRET_KEY: "<CHANGEME: blob-user-access-key-secret>"
kind: Secret
metadata:
  name: s3-blob-repository
  namespace: archived
type: Opaque
---
apiVersion: v1
stringData:
  # Password could be obtained from metadatadb-app secret after CloudNativePG
  # will create a new database
  #
  # Unfortunately it does not provide a complete URL for RO database instances
  # so this secret covers that case. If you have the only database instance you
  # can easily use RW instance just in manager or migrator do.
  #
  METADATA_DSN_RO: "postgresql://app:<CHANGEME: PostgreSQL database password>@metadatadb-ro.archived:5432/app"
kind: Secret
metadata:
  name: metadata-database-ro
  namespace: archived
type: Opaque
